.SH NAME
fm \- file manager
.SH SYNOPSIS
.B fm
.SH DESCRIPTION
A simple NCurses, C99, file manager for Posix with VI inspired keybinds.
.P
Note: Operations are delegated to system commands: rather than reinventing the
wheel.
.SH CONFIGURATION
Configuration is done by editing the config.h file and recompiling.

